version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    network_mode: "bridge"
    environment:
      - POSTGRES_USER=bluebell
      - POSTGRES_PASSWORD=dangerous
      - POSTGRES_DB=bluebell
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    network_mode: "bridge"
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass dangerous --loglevel warning
    volumes:
      - ./data/redis:/data