app:
  name: "bluebell"
  mode: "dev"
  version: "v1.0.0"
  port: 8080

log:
  level: "debug"
  filename: "./logs/bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

db:
  drive_name: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "dangerous"
  db_name: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: "dangerous"
  db: 0
  pool_size: 100

snowflake:
  start_time: "2021-10-25"
  machine_id: 1