app:
  name: "bluebell"
  addr: "0.0.0.0:8000"

log:
  level: "debug"
  filename: "./logs/bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

data:
  cache:
    addr: "127.0.0.1:6379"
    password: "dangerous"
    db: 0
    read_timeout: 1s
    write_timeout: 1s
  datasource:
    dsn: "postgres://bluebell:dangerous@127.0.0.1:5432/bluebell?sslmode=disable&TimeZone=Asia/Shanghai"

snowflake:
  start_time: "2021-10-25"
  machine_id: 1